### ISSUE TITLE
Error in rmultinom(length(which(Onset == t)), size = 1, prob = SI.Distr[t -  :    no positive probabilities

### ISSUE THREAD

**Issue by caijun** [annecori/EpiEstim#4]
Hi @annecori  When I used the Wallinga and Teunis method function `WT` to estimate the case reproduction number, it threw following error.

```
Error in rmultinom(length(which(Onset == t)), size = 1, prob = SI.Distr[t -  : 
  no positive probabilities
```

Here is my reproducible code

```
rm(list = ls())
load(url("http://tonytsai.name/41_Henan_stu_dec.rda"))

# plot epidemic curve
par(cex.main = 1.5, mfrow = c(1, 1), mar = c(2, 4, 2, 2.5))
plot(stu.dec$cases, type = "l")

# case reproduction number estimaion for pandemic
# using the Wallinga and Teunis method
t.start <- 130
Rc <- WT(stu.dec$cases, T.Start = t.start:359, T.End = (t.start + 6):365, method = "ParametricSI", 
         Mean.SI = 2.6, Std.SI = 1.3, plot = TRUE, nSim = 100)
```

I encountered the same error when the value of t.start is small; however, after I increased t.start to 130, it still threw the error. From the plot of epidemic curve, after the 130th day, there were enough cases. Could you please help me look at this problem? Thank you very much.

![image](https://cloud.githubusercontent.com/assets/2522593/20388283/1f372850-ac92-11e6-9f5a-280126d6ccdf.png)

Besides, I have implemented a method to automatically determine the minimum value of t.start that the `EstimateR` and `WT` functions can successfully complete the estimation of reproduction number without throwing a warning or an error. I think this would be a feature necessary to EpiEstim package.

**Comment by annecori** [comment]
Hi @caijun 
Thanks for reporting this bug. The issue was due to the very late isolated case in your dataset that appears at time 312; of course with the SI distribution you are using there is no way this case has been infected by one of the previous cases; I hadn't accounted for the possibility that such a long gap with no cases could happen. Should be sorted in the version I've just pushed - please as before just copy the WT function code from github - I need to work on the package soon!
I hope that helps
Thanks
Anne

**Comment by caijun** [comment]
It works, thank you very much @annecori
